### ISSUE TITLE
API Logs feature uses http: to try and download log files instead of https:

### ISSUE THREAD

**Issue by blairlierman** [docusign/esignature-recipes-python#1]
I spun up the site on Heroku, but when I click on a log entry to view it, I got a "Problem: Couldn't fetch the file" error. The URL it was trying to access was http, however my site was https. I was able to view the file after copying the URL and changing it to https.

Screenshot:
![apilogs01](https://cloud.githubusercontent.com/assets/11821485/17041483/2bb17b88-4f5b-11e6-8aeb-7e90c6520bc0.png)

**Comment by LarryKlugerDS** [comment]
Thank you for the issue report! I will look into it further.

**Comment by LarryKlugerDS** [comment]
I've updated the app to better detect https via proxies (eg on Heroku or ngrok). This solved the issue.
