### ISSUE TITLE
Requested runtime (python-2.7.11) is not available for this stack (heroku-18)

### ISSUE THREAD

**Issue by wardmanm** [docusign/esignature-recipes-python#2]
When attempting to deploy on heroku, the build process errors out with: 

Requested runtime (python-2.7.11) is not available for this stack (heroku-18).

**Comment by LarryKlugerDS** [comment]
Thank you. This is an older recipe and has been replaced by [eg-03-python-auth-code-grant](https://github.com/docusign/eg-03-python-auth-code-grant)

I will take this repo offline.
